name: CI
on:
    pull_request:
        branches:
            - devel
    push:
        branches:
            - master
            - devel
        tags:
            - "v*"

env:
    IMAGE_NAME: corp0/artemangaweb

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-python@v2
            -   name: Install requirements
                run: |
                    pip install poetry
                    poetry config virtualenvs.create false
                    poetry install
            -   name: Test
                env:
                    SECRET_KEY: secret
                    DB_ENGINE: django.db.backends.sqlite3
                run: |
                    cd src
                    python manage.py migrate
                    python manage.py test --no-input
    devel_build:
        needs: [ test ]
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Build Docker image
                run: |
                    docker pull $IMAGE_NAME
                    docker build --pull --cache-from $IMAGE_NAME -t $IMAGE_NAME .
    deploy:
        needs: [ devel_build ]
        if: ${{ github.event_name == 'push' }}
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Build image
                run: |
                    docker pull $IMAGE_NAME
                    docker build --pull --cache-from $IMAGE_NAME -t $IMAGE_NAME:latest .
            -   name: Log in into Docker Hub
                run: |
                    echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            -   name: Add a release tag to image
                if: contains(github.ref, 'refs/tags/')
                run: |
                    docker tag $IMAGE_NAME $IMAGE_NAME:${GITHUB_REF#refs/tags/}

            -   name: Push image to registry
                run: |
                    docker push $IMAGE_NAME
